# Generated by Django 2.2.3 on 2022-01-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ide', models.PositiveSmallIntegerField()),
                ('id_of', models.CharField(max_length=10)),
                ('paterno', models.CharField(max_length=50)),
                ('materno', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion_puesto', models.CharField(max_length=50)),
                ('descripcion_nivel_puesto', models.CharField(max_length=50)),
                ('descripcion_nivel', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('ultima_act', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
