# Generated by Django 2.2.3 on 2022-01-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0002_auto_20220119_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='ultima_act',
        ),
    ]
